---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2021/6/19 14:54
---

---table.concat(table,sep,start,end)
table1 = {1,3,5,7,9,11,13,15}
print(table.concat(table1))
print(table.concat(table1,","))
print(table.concat(table1,",",3))
print(table.concat(table1,",",3,5))
print("*********************")

---table.insert(表名，元素） 默认在末尾插入
---table.insert(表名，序号，元素） 在下标为指定序号的地方插入元素
---table.remove(表名） 默认移除最后一个元素
---table.remove(表名，序号）移除序号位置的元素
table.insert(table1,17)
print(table.concat(table1,","))
table.insert(table1,3,4)
print(table.concat(table1,","))
table.remove(table1)
print(table.concat(table1,","))
table.remove(table1,3)
print(table.concat(table1,","))
print("*********************")

---table.maxn(table)返回指定table中所有正数key值中最大的key值(key值即下标，不是value值）
---如果不存在key值为正数的元素，则返回0
print(table.maxn(table1))
print(table1[table.maxn(table1)])

---table.sort(table,[comp])
---对一个长度为length=n的数组table排序， 也就是对tab_table[1]到tab_table[n]排序，
---如果参数comp不省略，则它必须是一个函数，可以接收表tab_table的两个元素，
---并且在第一个元素小于第二个元素时返回true，其他情况返回false，
---如果省略参数comp，则Lua彼岸准运算符operator <将会被使用。

table2 = {9,11,13,15,1,3,5,7}
table.sort(table2)
print(table.concat(table2,","))
table.sort(table2,function(a, b) return a > b end )
print(table.concat(table2,","))
table.sort(table2,function(a, b) return a < b end )
print(table.concat(table2,","))